[package]
name = "gfret"
version = "2.1.0"
edition = "2021"
description = "Generates an svg template of a musical instrument fretboard"
authors = ["Nathan Fisher"]
repository = "https://codeberg.org/jeang3nie/gfret"
homepage = "https://jeang3nie.codeberg.page"
keywords = ["graphics", "design", "vector-graphics", "lutherie"]
categories = ["graphics", "multimedia::images", "mathematics", "simulation"]
license = "BSD-2-Clause"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fretboard_layout = "~0.3"
lazy_static = "~1.4"
svg = "~0.10"
toml = "~0.5"
clap = "~3.1"

[dependencies.gtk]
version = "~0.4"
package = "gtk4"

[dependencies.serde]
version = "~1.0"
features = ["derive"]

[dependencies.rgba_simple]
version = "~0.5"
features = ["gdk"]

[build-dependencies]
clap = "~3.1"
clap_complete = "~3.1"
