[package]
name = "gfret"
version = "0.2.0"
authors = ["Nathan Fisher <nfisher.sr@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.0.0-beta.2", features = ["yaml"] }
rug = "1.11"
svg = "0.8"
glib = "0.10.0"
gtk = "0.9.2"
gio = "0.9.1"
gdk-pixbuf = "0.9.0"

[profile.release]
panic = 'abort'
lto = true
codegen-units = 1
