[package]
name = "gfret"
version = "0.3.1"
authors = ["Nathan Fisher <nfisher.sr@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.0.0-beta.2", features = ["yaml"] }
gdk = "0.13.2"
gdk-pixbuf = "0.9.0"
gio = "0.9.1"
glib = "0.10.0"
gtk = "0.9.2"
lazy_static = "1.4"
serde = { version = "1.0", features = ["derive"] }
svg = "0.8"
toml = "0.5"
xdg-basedir = "1.0"

[dependencies.rug]
version = "1.12.0"
features = ["float"]

[profile.release]
panic = 'abort'
lto = true
codegen-units = 1
