[package]
name = "gfret2"
version = "1.99.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fretboard_layout = { git = "https://codeberg.org/jeang3nie/fretboard-layout.git" }
svg = "0.10.*"

[dependencies.gtk]
version = "0.1.*"
package = "gtk4"

[dependencies.clap]
version = "3.0.0-beta.2"
features = ["yaml"]
