[package]
name = "gfret2"
version = "1.99.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fretboard_layout = { git = "https://codeberg.org/jeang3nie/fretboard-layout.git" }
lazy_static = "~1.4"
svg = "~0.10"
toml = "~0.5"
xdg-basedir = "~1.0"

[dependencies.clap]
version = "3.0.0-beta.2"
features = ["yaml"]

[dependencies.gtk]
version = "~0.2"
package = "gtk4"

[dependencies.serde]
version = "~1.0"
features = ["derive"]

[dependencies.rgba_simple]
git = "https://codeberg.org/jeang3nie/rgba-simple.git"
features = ["gtk"]
