[package]
name = "gfret"
version = "1.99.6"
edition = "2021"
description = "Generates an svg template of a musical instrument fretboard"
authors = ["Nathan Fisher"]
repository = "https://codeberg.org/jeang3nie/gfret"
keywords = ["graphics", "design", "vector-graphics", "lutherie"]
categories = ["graphics", "multimedia::images", "mathematics", "simulation"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fretboard_layout = "~0.1"
lazy_static = "~1.4"
svg = "~0.10"
toml = "~0.5"
xdg-basedir = "~1.0"

[dependencies.clap]
version = "3.0.0-beta.2"

[dependencies.gtk]
version = "~0.3"
package = "gtk4"

[dependencies.serde]
version = "~1.0"
features = ["derive"]

[dependencies.rgba_simple]
version = "~0.4"
features = ["gdk"]
